variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  DOCKER_TLS_CERTDIR: "" 
  CRANE_VERSION: 0.19.2
  KUBE_URL: https://158.160.66.249
  REPO_URL: "https://camp-helm.gitlab.yandexcloud.net"
  PROJECT_ID: 2
  BRANCH: "main"
  REP_NAME: "papka"
  TARGET_PATH: "troyan.tar.gz"

stages:
  - build
  - release
  - deploy 

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - echo "test"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/application"
      --dockerfile "${CI_PROJECT_DIR}/application/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/application:$CI_COMMIT_SHA"
      --build-arg VERSION=$VERSION
      --cache=true


release:
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  cache: [ ]
  stage: release
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - crane tag $CI_REGISTRY_IMAGE/application:$CI_COMMIT_SHA $VERSION
  # rules:
  #   - changes:
  #     - application/*
  needs:
    - job: build

deploy:
  stage: deploy
  before_script:
    - set x
    - apt-get update
    - apt-get install curl -y
    # Install kubectl
    - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
  script:
    - | 
      URL="https://camp-helm.gitlab.yandexcloud.net/api/v4/projects/2/repository/archive.tar.gz?sha=main"
      wget -q -O "$TARGET_PATH" "$URL" > /dev/null 2>&1

      tar -xzvf $TARGET_PATH > /dev/null 2>&1 
      if [ -d "$REP_NAME" ]; then
          rm -rf "$REP_NAME"
      fi
      mv "camp_helm-$BRANCH"* "$REP_NAME"
      cd "$REP_NAME"
      ls -a    

